---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: v0.2.7


params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  BOSH_VM_FOLDER:
  BOSH_TEMPLATE_FOLDER:
  BOSH_DISK_PATH:
  ICMP_CHECKS_ENABLED:
  INFRA_NETWORK_NAME:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZS:
  AZ_1:
  AZ_1_CLUSTER_NAME:
  AZ_1_RP_NAME:
  NTP_SERVERS:
  OPS_DIR_HOSTNAME:
  ENABLE_VM_RESURRECTOR:
  MAX_THREADS:
  TRUSTED_CERTIFICATES:
  NSX_NETWORKING_ENABLED:
  NSX_ADDRESS:
  NSX_USERNAME:
  NSX_PASSWORD:
  NSX_CA_CERTIFICATE:

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/install-pcf/vsphere/tasks/config-opsdir/task.sh
